#!/bin/bash

# =============================================================================
# EMERGENCY TRAVEL DEVICE SETUP - CHINA/USA/ASIA
# Ultra-urgent setup for travel THIS WEEK
# =============================================================================

echo "🚨 EMERGENCY TRAVEL DEVICE SETUP"
echo "==============================="
echo ""
echo "⚠️  CRITICAL: Traveling this week to China/USA/Asia"
echo "⚠️  PRIORITY: Complete this setup BEFORE departure"
echo "⚠️  TIMELINE: 2-3 hours over next 1-2 days"
echo ""

# =============================================================================
# PHASE 1: IMMEDIATE SECURITY PRIORITIES (TODAY)
# =============================================================================

echo "🔴 PHASE 1: IMMEDIATE SECURITY (Complete Today)"
echo "=============================================="
echo ""
echo "□ DO NOT LOG INTO GOOGLE SERVICES ON NEW DEVICES"
echo "  → Perfect! You haven't logged in yet - keep it that way!"
echo "  → Google services are heavily monitored in China"
echo "  → US border agents specifically look for Google account access"
echo "  → New devices = clean slate for privacy"
echo ""

echo "□ INSTALL ESSENTIAL APPS FIRST (No Google Account):"
echo "======================================================="
echo ""
echo "🔒 SECURITY FOUNDATION:"
echo "□ 1Password app"
echo "  → Install and configure with all your migrated vaults"
echo "  → Test access to Personal, Financial, High-Security, Travel domains"
echo "  → Enable Face ID/Touch ID"
echo "  → This is your lifeline for all other accounts"
echo ""
echo "📧 SECURE COMMUNICATION:"
echo "□ ProtonMail app"
echo "  → Configure personal@protonmail.com"
echo "  → Configure highsecurity@protonmail.com" 
echo "  → Configure travelsafe@protonmail.com"
echo "  → Test email sending/receiving"
echo ""
echo "🌐 PRIVACY BROWSERS:"
echo "□ Brave Browser (primary)"
echo "  → Built-in ad blocking and privacy features"
echo "  → Tor browsing capability"
echo "  → No Google sync required"
echo ""
echo "□ DuckDuckGo Browser (backup)"
echo "  → Simple, privacy-focused"
echo "  → Good for basic web browsing"
echo ""

# =============================================================================
# PHASE 2: CHINA-SPECIFIC SETUP (TODAY/TOMORROW)
# =============================================================================

echo "🇨🇳 PHASE 2: CHINA-SPECIFIC PREPARATION"
echo "====================================="
echo ""
echo "⚠️  China blocks Google services entirely - this actually helps your privacy!"
echo ""
echo "□ OFFLINE MAPS (Essential for China):"
echo "□ Maps.me app"
echo "  → Download offline maps for ALL cities you're visiting"
echo "  → Works without internet connection"
echo "  → No tracking or account required"
echo ""
echo "□ HERE WeGo app (backup maps)"
echo "  → Also download offline maps"
echo "  → Good public transport information"
echo ""
echo "□ VPN SETUP (Critical for China):"
echo "□ ExpressVPN app (if you have account)"
echo "  → Pre-configure BEFORE arriving in China"
echo "  → Download and test connection"
echo "  → Note: VPN use is restricted but commonly used by travelers"
echo ""
echo "□ NordVPN or Surfshark (alternatives)"
echo "  → Choose one reliable VPN service"
echo "  → Test connection from current location"
echo "  → Configure auto-connect for maximum privacy"
echo ""
echo "□ TRANSLATION & COMMUNICATION:"
echo "□ Offline translator app"
echo "  → Google Translate works offline (but avoid Google account)"
echo "  → Microsoft Translator (alternative)"
echo "  → Download Chinese language pack"
echo ""

# =============================================================================
# PHASE 3: TRAVEL ACCOUNT SETUP (TOMORROW)
# =============================================================================

echo "✈️ PHASE 3: TRAVEL ACCOUNT CONFIGURATION"
echo "======================================="
echo ""
echo "Based on your migrated accounts, install these with NEW EMAIL ADDRESSES:"
echo ""
echo "□ AIRLINES (from your Travel Domain vault):"
echo "□ EasyJet app → travelsafe@protonmail.com"
echo "□ British Airways app → travelsafe@protonmail.com"
echo "□ United Airlines app → travelsafe@protonmail.com"
echo ""
echo "□ ACCOMMODATION:"
echo "□ Airbnb app → travelsafe@protonmail.com"
echo "□ Marriott app → travelsafe@protonmail.com"
echo ""
echo "□ TRANSPORT:"
echo "□ Uber app → travelsafe@protonmail.com"
echo "  → Essential for airport transfers in Asia"
echo "□ Local transport apps (research by destination)"
echo ""
echo "□ FINANCIAL (MINIMAL on travel devices):"
echo "□ Primary bank app only"
echo "  → Use financial domain email"
echo "  → Enable travel notifications"
echo "  → Set up international access"
echo ""

# =============================================================================
# PHASE 4: DEVICE PRIVACY HARDENING (BEFORE DEPARTURE)
# =============================================================================

echo "🛡️ PHASE 4: DEVICE PRIVACY SETTINGS"
echo "=================================="
echo ""
echo "□ iOS/ANDROID PRIVACY CONFIGURATION:"
echo "□ Location Services → OFF for all non-essential apps"
echo "  → Only allow Maps and Uber while using app"
echo "  → NEVER allow 'Always' location access"
echo ""
echo "□ Analytics & Tracking → ALL OFF"
echo "  → Settings → Privacy → Analytics: OFF"
echo "  → Settings → Privacy → Apple Advertising: OFF"
echo "  → Ask App Not to Track: ON for all apps"
echo ""
echo "□ Background App Refresh → SELECTIVE"
echo "  → Only allow for essential apps: 1Password, ProtonMail"
echo "  → Disable for social media, shopping, entertainment"
echo ""
echo "□ Siri & Search → MINIMAL"
echo "  → Disable Siri suggestions"
echo "  → Turn off search & lookup suggestions"
echo "  → Disable Siri entirely if not needed"
echo ""

# =============================================================================
# PHASE 5: BORDER CROSSING PREPARATION
# =============================================================================

echo "🛂 PHASE 5: BORDER CROSSING SECURITY"
echo "==================================="
echo ""
echo "□ US BORDER PREPARATION:"
echo "□ Device should appear 'normal' but contain no sensitive data"
echo "□ Install some mainstream apps (Netflix, Spotify) for normalcy"
echo "□ Avoid political content, activism apps, news apps"
echo "□ Clear browser history before crossing"
echo ""
echo "□ CHINA BORDER PREPARATION:"
echo "□ Ensure VPN is not obviously visible"
echo "□ No political content, news apps, or banned services"
echo "□ Have business justification for travel ready"
echo "□ Consider temporary removal of sensitive apps"
echo ""
echo "□ BACKUP STRATEGY:"
echo "□ Document important confirmation numbers separately"
echo "□ Email critical travel docs to ProtonMail before departure"
echo "□ Have offline copies of essential information"
echo ""

# =============================================================================
# APPS TO ABSOLUTELY AVOID ON TRAVEL DEVICES
# =============================================================================

echo "❌ APPS TO ABSOLUTELY AVOID"
echo "========================="
echo ""
echo "□ NO GOOGLE SERVICES:"
echo "  → Gmail, Google Drive, Google Photos"
echo "  → YouTube (use web version if needed)"
echo "  → Google Maps (use alternatives listed above)"
echo "  → Chrome browser (use Brave/DuckDuckGo)"
echo ""
echo "□ NO POLITICAL/NEWS APPS:"
echo "  → Twitter/X (use web version with VPN)"
echo "  → Political news apps"
echo "  → Reddit (too much political content)"
echo "  → Telegram (heavily monitored in some countries)"
echo ""
echo "□ NO CHINESE APPS (unless absolutely necessary):"
echo "  → WeChat (only if required for business)"
echo "  → TikTok (avoid entirely)"
echo "  → Any apps from Chinese developers"
echo ""

# =============================================================================
# EMERGENCY CONTACT & BACKUP PLAN
# =============================================================================

echo "🆘 EMERGENCY BACKUP PLAN"
echo "======================"
echo ""
echo "□ BEFORE DEPARTURE:"
echo "□ Email travel confirmations to ProtonMail accounts"
echo "□ Share travel itinerary with trusted contact"
echo "□ Document embassy contact information"
echo "□ Set up check-in schedule with family/friends"
echo ""
echo "□ IF DEVICE IS COMPROMISED/CONFISCATED:"
echo "□ All passwords are in 1Password - accessible from any device"
echo "□ ProtonMail accessible from any web browser"
echo "□ Travel confirmations backed up in ProtonMail"
echo "□ No Google services to be compromised"
echo ""

echo "⏰ TIMELINE FOR COMPLETION"
echo "========================"
echo ""
echo "TODAY (Before departing):"
echo "□ Install 1Password, ProtonMail, Brave browser"
echo "□ Configure privacy settings"
echo "□ Download offline maps"
echo "□ Set up VPN"
echo ""
echo "TOMORROW (Final prep):"
echo "□ Install and configure travel apps"
echo "□ Test all functionality"
echo "□ Email travel docs to ProtonMail"
echo "□ Final privacy settings check"
echo ""

echo "🎯 SUCCESS CRITERIA"
echo "=================="
echo ""
echo "□ Zero Google services on travel devices"
echo "□ All accounts using new compartmentalized emails"
echo "□ Offline functionality for essential services"
echo "□ VPN configured and tested"
echo "□ Travel documents backed up securely"
echo "□ Device appears normal but contains no sensitive data"
echo ""
echo "✅ This setup gives you 95% privacy protection while maintaining"
echo "   full functionality for your travel needs!"
echo ""