#!/bin/bash

# =============================================================================
# TRAVEL PHONE SETUP - CHINA/USA/ASIA
# Step-by-step phone configuration for secure travel
# =============================================================================

echo "📱 TRAVEL PHONE SETUP CHECKLIST"
echo "==============================="
echo ""
echo "🎯 Goal: Privacy-focused phone setup for China/USA/Asia travel"
echo "⏰ Time: 60-90 minutes total"
echo "🚨 Critical: Complete BEFORE departure"
echo ""

# =============================================================================
# STEP 1: FOUNDATION APPS (INSTALL FIRST)
# =============================================================================

echo "🔒 STEP 1: FOUNDATION APPS (30 minutes)"
echo "======================================"
echo ""
echo "Install these apps FIRST, in this exact order:"
echo ""

echo "□ 1Password App"
echo "==============="
echo "1. Download from App Store/Google Play"
echo "2. Sign in with your existing 1Password account"
echo "3. VERIFY you can access ALL vaults:"
echo "   - Personal Domain vault ✓"
echo "   - Financial Domain vault ✓"
echo "   - High-Security Domain vault ✓"  
echo "   - Travel Domain vault ✓"
echo "4. Enable Face ID/Touch ID"
echo "5. Test autofill in Safari/Chrome"
echo "6. ✅ CRITICAL: Don't proceed until this works perfectly!"
echo ""

echo "□ ProtonMail App"
echo "================"
echo "1. Download official ProtonMail app"
echo "2. Add your three ProtonMail accounts:"
echo "   - Personal domain email"
echo "   - High-security domain email"
echo "   - travelsafe@protonmail.com"
echo "3. Test sending a test email from each account"
echo "4. Enable push notifications ONLY for travelsafe email"
echo "5. Set travelsafe@protonmail.com as default for new emails"
echo ""

echo "□ Brave Browser"
echo "==============="
echo "1. Download Brave Browser (NOT Chrome!)"
echo "2. Set as default browser when prompted"
echo "3. Go to Settings → Privacy & Security:"
echo "   - Block fingerprinting: Aggressive"
echo "   - Block all device recognition attempts: ON"
echo "   - Clear data on exit: ON"
echo "4. Enable Tor private browsing (for China if needed)"
echo "5. ✅ Test: Browse to a website, verify no tracking"
echo ""

# =============================================================================
# STEP 2: PHONE PRIVACY SETTINGS (CRITICAL)
# =============================================================================

echo "🛡️ STEP 2: PHONE PRIVACY SETTINGS (20 minutes)"
echo "=============================================="
echo ""

echo "□ iOS Privacy Settings:"
echo "======================"
echo "1. Settings → Privacy & Security → Location Services"
echo "   - Turn OFF 'Share My Location'"
echo "   - Turn OFF 'Find My iPhone' location sharing"
echo "   - System Services → ALL OFF except 'Find My iPhone'"
echo ""
echo "2. Settings → Privacy & Security → Analytics & Improvements"
echo "   - Share iPhone Analytics: OFF"
echo "   - Share iCloud Analytics: OFF"
echo "   - Improve Siri & Dictation: OFF"
echo ""
echo "3. Settings → Privacy & Security → Apple Advertising"
echo "   - Personalized Ads: OFF"
echo ""
echo "4. Settings → Privacy & Security → Tracking"
echo "   - Allow Apps to Request to Track: OFF"
echo ""
echo "5. Settings → Siri & Search"
echo "   - Listen for 'Hey Siri': OFF"
echo "   - Use Siri when locked: OFF"
echo "   - Siri Suggestions: ALL OFF"
echo ""

echo "□ Android Privacy Settings:"
echo "=========================="
echo "1. Settings → Privacy → Permission manager"
echo "   - Location: Review and restrict ALL non-essential apps"
echo "   - Camera: Only allow for essential apps"
echo "   - Microphone: Only allow for calling apps"
echo ""
echo "2. Settings → Google → Ads"
echo "   - Opt out of Ads Personalization: ON"
echo "   - Reset advertising ID"
echo ""
echo "3. Settings → Privacy → Activity controls"
echo "   - Web & App Activity: OFF"
echo "   - Location History: OFF"
echo "   - YouTube History: OFF"
echo ""

# =============================================================================
# STEP 3: CHINA-SPECIFIC TOOLS
# =============================================================================

echo "🇨🇳 STEP 3: CHINA-SPECIFIC TOOLS (20 minutes)"
echo "============================================="
echo ""

echo "□ Offline Maps (ESSENTIAL for China)"
echo "===================================="
echo "1. Install Maps.me app"
echo "2. Search for your destination cities in China"
echo "3. Download offline maps for EACH city you're visiting"
echo "4. Test navigation without internet connection"
echo "5. Bookmark your hotel locations"
echo ""
echo "6. Install HERE WeGo (backup maps)"
echo "7. Download same cities for redundancy"
echo "8. Test public transport directions"
echo ""

echo "□ VPN Setup (CRITICAL for China)"
echo "================================"
echo "1. Choose ONE VPN service:"
echo "   - ExpressVPN (recommended for China)"
echo "   - NordVPN (good alternative)"
echo "   - Surfshark (budget option)"
echo ""
echo "2. Install and configure VPN:"
echo "   - Create account and subscribe"
echo "   - Download official app"
echo "   - Test connection from current location"
echo "   - Set to auto-connect on untrusted networks"
echo "   - Choose Hong Kong or Japan servers for China"
echo ""
echo "⚠️  Note: VPN use has legal restrictions in China"
echo "   Use responsibly and be aware of local laws"
echo ""

echo "□ Translation App"
echo "================="
echo "1. Install Microsoft Translator (works offline)"
echo "2. Download Chinese (Simplified) language pack"
echo "3. Test offline translation functionality"
echo "4. Enable camera translation for signs/menus"
echo ""

# =============================================================================
# STEP 4: TRAVEL APPS WITH NEW EMAILS
# =============================================================================

echo "✈️ STEP 4: TRAVEL APPS WITH NEW EMAILS (30 minutes)"
echo "=================================================="
echo ""
echo "Now install travel apps using your NEW compartmentalized emails:"
echo ""

echo "□ Airlines (Use Travel Domain vault passwords)"
echo "=============================================="
echo "1. EasyJet app → Log in with travelsafe@protonmail.com"
echo "   - Use password from 1Password Travel vault"
echo "   - Enable mobile check-in"
echo "   - Turn OFF location tracking"
echo ""
echo "2. British Airways app → Log in with travelsafe@protonmail.com"
echo "   - Use password from 1Password Travel vault"
echo "   - Download boarding passes offline"
echo "   - Disable marketing notifications"
echo ""
echo "3. United Airlines app → Log in with travelsafe@protonmail.com"
echo "   - Use password from 1Password Travel vault"
echo "   - Set up mobile boarding passes"
echo "   - Turn OFF location services"
echo ""

echo "□ Accommodation & Transport"
echo "==========================="
echo "1. Airbnb app → Log in with travelsafe@protonmail.com"
echo "   - Use 1Password for login"
echo "   - Download offline property details"
echo "   - Turn OFF location tracking when not in use"
echo ""
echo "2. Uber app → Log in with travelsafe@protonmail.com"
echo "   - Essential for airport transfers in Asia"
echo "   - Allow location ONLY while using app"
echo "   - Set up payment method (use travel credit card)"
echo ""
echo "3. Marriott app → Log in with travelsafe@protonmail.com"
echo "   - Use for hotel check-in"
echo "   - Download confirmation details offline"
echo ""

echo "□ Essential Financial (MINIMAL)"
echo "==============================="
echo "1. Your PRIMARY bank app only"
echo "   - Use Financial domain email from 1Password"
echo "   - Enable international transaction alerts"
echo "   - Set up travel notifications"
echo "   - Enable 2FA with 1Password"
echo ""
echo "2. Credit card app (travel card only)"
echo "   - Notify of international travel"
echo "   - Set up fraud alerts"
echo "   - Download offline customer service numbers"
echo ""

# =============================================================================
# STEP 5: APP PERMISSIONS LOCKDOWN
# =============================================================================

echo "🔒 STEP 5: APP PERMISSIONS LOCKDOWN (15 minutes)"
echo "=============================================="
echo ""
echo "For EVERY app you install, review these permissions:"
echo ""

echo "□ Location Permissions"
echo "====================="
echo "- Maps apps: 'While Using App' only"
echo "- Uber: 'While Using App' only"
echo "- Airlines: 'Never' (not needed)"
echo "- Hotels: 'Never' (not needed)"
echo "- Banking: 'Never' (not needed)"
echo "- ALL other apps: 'Never'"
echo ""

echo "□ Camera & Microphone"
echo "===================="
echo "- Translation app: Allow Camera for sign translation"
echo "- Banking apps: Allow Camera for check deposits"
echo "- All other apps: DENY"
echo ""

echo "□ Notifications"
echo "==============="
echo "- ProtonMail (travelsafe only): Allow"
echo "- Airlines: Allow for flight updates"
echo "- Banking: Allow for fraud alerts"
echo "- All other apps: Disable or 'Deliver Quietly'"
echo ""

echo "□ Background App Refresh"
echo "======================="
echo "- 1Password: ON"
echo "- ProtonMail: ON"
echo "- Banking: ON"
echo "- All other apps: OFF"
echo ""

# =============================================================================
# STEP 6: FINAL SECURITY CHECKS
# =============================================================================

echo "✅ STEP 6: FINAL SECURITY VERIFICATION (10 minutes)"
echo "=================================================="
echo ""

echo "□ Test Everything:"
echo "=================="
echo "1. 1Password autofill works in all apps ✓"
echo "2. ProtonMail sends/receives from all accounts ✓"
echo "3. Offline maps work without internet ✓"
echo "4. VPN connects and changes IP address ✓"
echo "5. All travel apps log in with new emails ✓"
echo "6. Banking app works with international settings ✓"
echo ""

echo "□ Email Critical Documents:"
echo "=========================="
echo "1. Forward flight confirmations to travelsafe@protonmail.com"
echo "2. Email hotel confirmations and addresses"
echo "3. Send yourself emergency contact information"
echo "4. Email important phone numbers (embassy, insurance)"
echo ""

echo "□ Backup Plan:"
echo "=============="
echo "1. Write down important confirmation numbers"
echo "2. Screenshot key travel documents"
echo "3. Share itinerary with trusted contact at home"
echo "4. Know how to access 1Password from any device"
echo ""

# =============================================================================
# APPS TO ABSOLUTELY AVOID
# =============================================================================

echo "❌ APPS TO ABSOLUTELY AVOID ON TRAVEL PHONE"
echo "==========================================="
echo ""
echo "DO NOT INSTALL:"
echo "- Gmail, Google Drive, Google Photos"
echo "- YouTube app (use web version if needed)"
echo "- Google Maps (you have offline alternatives)"
echo "- Chrome browser (you have Brave)"
echo "- Twitter/X app (use web with VPN if needed)"
echo "- Reddit app (political content risky)"
echo "- TikTok (avoid entirely)"
echo "- WeChat (only if absolutely required for business)"
echo "- Any Chinese apps unless essential"
echo ""

echo "🎯 SUCCESS CRITERIA"
echo "=================="
echo ""
echo "Your phone is ready when:"
echo "□ Zero Google services installed"
echo "□ All apps use compartmentalized emails"
echo "□ Offline functionality for maps and translation"
echo "□ VPN configured and tested"
echo "□ Privacy settings maximized"
echo "□ Travel documents backed up in ProtonMail"
echo "□ Banking apps configured for international use"
echo "□ Emergency contact information accessible"
echo ""

echo "🌍 You're now ready for secure travel to China/USA/Asia!"
echo "Your phone provides full functionality while maintaining maximum privacy."
echo ""